version: "3.7"

services:
  web:
    build: ./src
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=sam
      - POSTGRES_PASSWORD=hello_flask
      - POSTGRES_DB=financeme_db

volumes:
  postgres_data:
